"""
AUTOINTEL SETUP — Run this ONCE before starting the agent
=========================================================
Creates two data sources:
  1. autointel.db  -> SQLite database with vehicle telemetry (structured data)
  2. ChromaDB      -> Vector database with automotive knowledge (unstructured data)

This simulates what a real Data Engineer builds:
  - Structured data  = historian/MES database (like HighByte feeds into)
  - Unstructured data = engineering docs, specs, manuals
"""

import sqlite3
import os
import sys
import random
from datetime import datetime, timedelta

# LangChain used here for smart document chunking (this is its real value)
from langchain_text_splitters import RecursiveCharacterTextSplitter
import chromadb
from sentence_transformers import SentenceTransformer

# ============================================================
# AUTOMOTIVE KNOWLEDGE BASE
# (embedded directly — no separate file needed)
# ============================================================
AUTOMOTIVE_KNOWLEDGE = """
SECTION: TORQUE AND POWER
Torque is the rotational force produced by an engine, measured in Newton-metres (Nm).
It determines acceleration from standstill and the pulling power of the vehicle.
BHP or Brake Horsepower measures the actual engine output at the crankshaft.
The formula connecting torque and power is: BHP = (Torque_Nm multiplied by RPM) divided by 7127.
Peak torque in diesel engines and EV motors is available from very low RPM giving strong low-end pull.
Petrol engines typically develop peak torque higher in the rev range.
Flat torque curves common in EVs give strong and consistent acceleration across the entire speed range.
Torque vectoring distributes drive force between individual wheels to improve cornering stability and traction.
Power-to-weight ratio in BHP per tonne is a key metric for comparing vehicle performance potential.
A higher power to weight ratio directly translates to faster acceleration and better track performance.

SECTION: VEHICLE AERODYNAMICS
The drag coefficient Cd quantifies how much aerodynamic drag a vehicle generates moving through air.
A lower Cd means less air resistance, better efficiency, and higher top speed potential.
Typical passenger cars have Cd between 0.25 and 0.35. Performance sports cars can achieve 0.22 to 0.29.
Downforce is generated by aerodynamic elements like front splitters, rear diffusers, and rear wings.
These elements create a pressure difference that pushes the car downward into the road surface.
More downforce increases cornering grip significantly but also increases aerodynamic drag as a penalty.
Aerodynamic drag force formula: Force equals 0.5 multiplied by Cd multiplied by frontal area multiplied by air density multiplied by velocity squared.
At 200 kilometres per hour aerodynamic drag consumes a disproportionately large share of engine power.
This square relationship with speed means drag quadruples when speed doubles.
The frontal area multiplied by Cd gives a combined drag figure used to compare vehicles directly.

SECTION: TURBOCHARGED AND SUPERCHARGED ENGINES
Turbochargers use exhaust gases to spin a turbine that forces more air into the engine intake.
More compressed air allows more fuel combustion per cycle producing significantly more power.
Turbo lag is the delay between throttle input and when boost pressure builds up, typically 0.5 to 1.5 seconds.
Twin-scroll turbochargers separate exhaust pulses from different cylinders improving response and reducing lag.
Variable geometry turbines adjust blade angle to optimise boost across the entire RPM range.
Superchargers are mechanically driven by a belt from the crankshaft providing instant boost with zero lag.
Intercoolers cool the compressed intake air increasing its density and reducing the risk of engine knock.
Twin turbo setups use two smaller turbos mounted in parallel or sequence to balance power and response.
Boost pressure is typically measured in bar or PSI above standard atmospheric pressure.

SECTION: ELECTRIC VEHICLE DRIVETRAINS
EV motors produce maximum torque from zero RPM giving instant and linear acceleration response.
This is fundamentally different from combustion engines that must rev up to reach peak torque.
Dual motor EVs place one motor per axle enabling all-wheel drive with precise individual wheel torque control.
Battery capacity measured in kilowatt hours determines the total energy available and therefore the driving range.
Peak power measured in kilowatts determines acceleration performance and maximum sustained output.
Regenerative braking converts kinetic energy back to electrical energy during deceleration.
This energy recovery can improve overall efficiency by 15 to 20 percent in urban driving conditions.
EV motor efficiency typically exceeds 90 percent compared to 35 to 40 percent for petrol combustion engines.
Thermal management of battery cells is critical for both performance and long-term battery health.
Lithium ion cells perform optimally between 20 and 40 degrees Celsius and degrade outside this range.

SECTION: SUSPENSION AND HANDLING DYNAMICS
Lateral g-force measures the cornering acceleration force experienced by the vehicle and occupants.
Standard road cars comfortably sustain 0.8 to 1.0g during hard cornering manoeuvres.
High-performance track cars with significant downforce can sustain 1.2 to 1.5g or more in corners.
Suspension geometry parameters including camber, toe angle, and caster angle affect tyre contact patch shape.
Negative camber tilts the tyre top inward improving cornering grip at the cost of straight-line tyre wear.
Adaptive dampers adjust their stiffness in real time based on road inputs and selected driving mode.
Weight distribution close to 50 percent front and 50 percent rear provides the most balanced handling.
A lower centre of gravity reduces body roll in corners and improves transient response to steering inputs.
Anti-roll bars connect left and right suspension sides to limit body roll during cornering.

SECTION: THERMAL MANAGEMENT IN VEHICLES
Normal engine operating temperature range is typically 85 to 105 degrees Celsius for most petrol engines.
Operating consistently above this range risks pre-ignition, detonation, and accelerated wear of components.
EV battery thermal management systems use liquid cooling loops or air cooling to maintain the optimal temperature window.
Brake fade occurs when brake discs and pads overheat reducing the friction coefficient and stopping power.
Carbon ceramic brakes resist fade far better than iron discs making them preferred for track and high-speed use.
Engine oil viscosity decreases as temperature rises which reduces its effectiveness as a lubricant under load.
Radiators dissipate engine heat by transferring it from coolant to air flowing through the front of the vehicle.
Turbocharged engines generate substantially more heat than naturally aspirated units requiring larger cooling systems.
"""

# ============================================================
# VEHICLE FLEET DATA
# ============================================================
VEHICLES = [
    (1, "Mahindra XEV 9e",     "EV SUV",        "Dual Electric Motor",     288, 380, 2195, 0.28),
    (2, "Tata Curvv EV",       "EV Coupe SUV",  "Single Electric Motor",   167, 215, 1800, 0.29),
    (3, "BMW M3 Competition",  "Sports Sedan",  "S58 3.0L Twin-Turbo I6",  510, 650, 1730, 0.31),
    (4, "Toyota GR86",         "Sports Coupe",  "FA24 2.4L Boxer",         234, 250, 1270, 0.27),
    (5, "Maruti Suzuki Swift", "Hatchback",     "Z12E 1.2L Mild Hybrid",    82, 112,  905, 0.30),
]


def create_telemetry_database():
    """
    Creates SQLite database with vehicle specs and simulated telemetry.
    This represents what HighByte / a data historian would store from real vehicle ECUs.
    """
    print("\n" + "="*55, flush=True)
    print("Creating vehicle telemetry database...", flush=True)
    print("="*55, flush=True)

    conn = sqlite3.connect("autointel.db")
    cursor = conn.cursor()

    # Drop and recreate tables for a clean setup
    cursor.execute("DROP TABLE IF EXISTS telemetry")
    cursor.execute("DROP TABLE IF EXISTS vehicles")

    cursor.execute("""
        CREATE TABLE vehicles (
            id                INTEGER PRIMARY KEY,
            name              TEXT,
            type              TEXT,
            engine            TEXT,
            max_bhp           INTEGER,
            max_torque_nm     INTEGER,
            weight_kg         INTEGER,
            drag_coefficient  REAL
        )
    """)

    cursor.execute("""
        CREATE TABLE telemetry (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            vehicle_id    INTEGER,
            timestamp     TEXT,
            speed_kmh     REAL,
            rpm           INTEGER,
            torque_nm     REAL,
            bhp           REAL,
            throttle_pct  REAL,
            brake_pct     REAL,
            lateral_g     REAL,
            engine_temp_c REAL,
            FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
        )
    """)

    cursor.executemany(
        "INSERT INTO vehicles VALUES (?,?,?,?,?,?,?,?)", VEHICLES
    )
    print(f"   Inserted {len(VEHICLES)} vehicles into database", flush=True)

    # Generate realistic telemetry readings for each vehicle
    base_time = datetime(2026, 6, 1, 9, 0, 0)
    telemetry_rows = []
    random.seed(42)  # Fixed seed for reproducible data

    for v_id, _, _, _, max_bhp, max_torque, weight, _ in VEHICLES:
        for i in range(30):
            ts = (base_time + timedelta(minutes=i * 5)).isoformat()
            throttle = round(random.uniform(20, 95), 1)
            rpm = int(random.uniform(1500, 7000))
            torque = round(max_torque * (throttle / 100) * random.uniform(0.7, 1.0), 1)
            bhp = round((torque * rpm) / 7127, 1)
            speed = round(random.uniform(30, 220), 1)
            lat_g = round(random.uniform(0.1, 1.3), 2)
            eng_temp = round(random.uniform(78, 108), 1)
            brake = round(max(0, min(100, 100 - throttle + random.uniform(-10, 10))), 1)
            telemetry_rows.append(
                (v_id, ts, speed, rpm, torque, bhp, throttle, brake, lat_g, eng_temp)
            )

    cursor.executemany("""
        INSERT INTO telemetry
        (vehicle_id, timestamp, speed_kmh, rpm, torque_nm, bhp,
         throttle_pct, brake_pct, lateral_g, engine_temp_c)
        VALUES (?,?,?,?,?,?,?,?,?,?)
    """, telemetry_rows)

    conn.commit()
    conn.close()
    print(f"   Inserted {len(telemetry_rows)} telemetry readings", flush=True)
    print("   autointel.db created successfully!", flush=True)


def create_knowledge_base():
    """
    Chunks automotive knowledge using LangChain's RecursiveCharacterTextSplitter,
    embeds with sentence-transformers, and stores in ChromaDB.

    LangChain's splitter is smarter than simple character slicing —
    it tries to split on paragraphs, then sentences, then words.
    """
    print("\n" + "="*55, flush=True)
    print("Creating automotive knowledge base (ChromaDB)...", flush=True)
    print("="*55, flush=True)

    # LangChain smart chunking — this is why LangChain adds value over manual slicing
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=400,
        chunk_overlap=60,       # Overlap prevents losing context at chunk boundaries
        separators=["\n\n", "\n", ". ", " "]
    )

    chunks = splitter.split_text(AUTOMOTIVE_KNOWLEDGE)
    print(f"   LangChain split knowledge into {len(chunks)} smart chunks", flush=True)

    print("   Loading embedding model...", flush=True)
    embedder = SentenceTransformer("all-MiniLM-L6-v2")
    print("   Embedding model loaded!", flush=True)

    print("   Storing in ChromaDB...", flush=True)
    chroma_client = chromadb.PersistentClient(path="./chroma_db")

    # Delete existing collection if it exists for clean setup
    try:
        chroma_client.delete_collection("automotive_knowledge")
    except Exception:
        pass

    collection = chroma_client.create_collection("automotive_knowledge")
    embeddings = embedder.encode(chunks).tolist()

    collection.add(
        documents=chunks,
        embeddings=embeddings,
        ids=[f"chunk_{i}" for i in range(len(chunks))]
    )

    print(f"   {len(chunks)} chunks stored in ChromaDB!", flush=True)
    print("   chroma_db/ folder created successfully!", flush=True)


if __name__ == "__main__":
    print("\n AUTOINTEL SETUP", flush=True)
    print(" Building your automotive data infrastructure...", flush=True)

    create_telemetry_database()
    create_knowledge_base()

    print("\n" + "="*55, flush=True)
    print(" SETUP COMPLETE! You now have:", flush=True)
    print("   autointel.db  -> Vehicle telemetry database (SQLite)", flush=True)
    print("   chroma_db/    -> Automotive knowledge base (ChromaDB)", flush=True)
    print("\n Next step: run  python app.py  for the web UI", flush=True)
    print("        OR: run  python agent.py  for terminal mode", flush=True)
    print("="*55, flush=True)
